name = "sveltesummit-fall-2021"
type = 'webpack'
account_id = '8d17b159c1762092c249ba7ed2318384'
zone_id = '2f26e10be154be3411d718541fb12d3a'
usage_model = ''
route = 'https://sveltesummit.com/*'
workers_dev = true
target_type = "webpack"
[site]
bucket = "./build"
entry-point = "workers-site"

compatibility_date = "2021-10-13"